# Generated by Django 5.1.15 on 2026-07-30 12:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_artist_created_at_remove_artist_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='meetings/'),
            preserve_default=False,
        ),
    ]
