# Generated by Django 5.1.15 on 2026-08-04 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_courseregistration_reminder_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseregistration',
            name='reminder_sent',
        ),
        migrations.RemoveField(
            model_name='meetingregistration',
            name='reminder_sent',
        ),
    ]
