# Generated by Django 5.1.15 on 2026-08-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_courseregistration_reminder_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistration',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetingregistration',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
