# Generated by Django 5.1.15 on 2026-08-18 08:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_courseregistration_reminder_sent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseregistration',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='meetingregistration',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='courseregistration',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='unique_user_course_registration'),
        ),
        migrations.AddConstraint(
            model_name='meetingregistration',
            constraint=models.UniqueConstraint(fields=('user', 'meeting'), name='unique_user_meeting_registration'),
        ),
    ]
