# Generated by Django 5.1.15 on 2026-08-18 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_courseregistration_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PastEvent',
        ),
    ]
